# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'

    indices:
    - name: products
      class: App\Entity\Product
      enable_serializer_groups: true

    indices:
    - name: companies
      class: App\Entity\Company
      enable_serializer_groups: true

    indices:
    - name: adresses
      class: App\Entity\Addres
      enable_serializer_groups: true
